#ifndef __CEXIL_PIXEL_MAPPING_H
#define __CEXIL_PIXEL_MAPPING_H

#define CEXIL_PIXEL_MAPPING_LENGTH 256
#define CEXIL_PIXEL_MAPPING_STRING_LENGTH 3

extern char cexil_pixel_mapping[
  CEXIL_PIXEL_MAPPING_LENGTH
][
  CEXIL_PIXEL_MAPPING_STRING_LENGTH
];

#endif

