name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: build_library
      run: mkdir -p objects && mkdir -p fonts/cexil_font_transpiler/objects && make

    - name: build_examples
      run: make examples
